*NUMPY NOTEBOOK*

In [1]:
#importing the numpy module
import numpy as np

Generating Numpy Arrays

In [2]:
#creating a numpy array from a list
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)
print(type(data))

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>


In [3]:
#creating a numpy array of integers from a list 
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [4]:
#creating a numpy array of floats from a list
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [5]:
#creating a numpy array of complex numbers from a list
data=np.array([1, 2, 3], dtype=np.complex)
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
data.real

array([1., 2., 3.])

In [7]:
data.imag

array([0., 0., 0.])

In [8]:
#creating a numpy array of zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
#creating a numpy array of ones
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
data=np.empty(3)
data

array([0., 0., 0.])

In [11]:
data.fill(2)

In [12]:
data

array([2., 2., 2.])

In [13]:
#creating an identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [15]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

Slicing

In [16]:
data=np.arange(0,11,1)

In [17]:
data[0]

0

In [18]:
data[0:4]

array([0, 1, 2, 3])

In [19]:
data[-1]

10

In [20]:
data[-3:]

array([ 8,  9, 10])

In [21]:
data[2:6]

array([2, 3, 4, 5])

In [22]:
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [23]:
A[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [24]:
B = A[1:5, 1:5]

In [25]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [26]:
B[:,:]=0

In [27]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [28]:
C = B[1:3, 1:3].copy()
print(C)
C[:, :] = 1
print(C)

[[0 0]
 [0 0]]
[[1 1]
 [1 1]]


In [29]:
print(B)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [30]:
data = np.linspace(0, 1, 11)

In [31]:
data>0.4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [32]:
data[data>0.4]

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [33]:
data = np.array([[1, 2], [3, 4]])
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [34]:
data = np.arange(5)
print(data)
np.vstack((data, data, data))

[0 1 2 3 4]


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [35]:
data = np.arange(5)
print(data)
np.hstack((data, data, data))

[0 1 2 3 4]


array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [36]:
data = data[:, np.newaxis]
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

Arithmetic Operations

In [37]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [3, 4]])

In [38]:
x+y

array([[2, 4],
       [6, 8]])

In [39]:
x*2

array([[2, 4],
       [6, 8]])

In [40]:
x/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [41]:
x = np.linspace(-1, 1, 11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [42]:
y = np.sin(np.pi * x)
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [43]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])